---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teamspeak
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./service-tcp.yaml
labels:
  - pairs:
      app.kubernetes.io/name: teamspeak
      app.kubernetes.io/instance: teamspeak
