apiVersion: v1
kind: Service
metadata:
  name: teamspeak-app
  namespace: teamspeak
  labels:
    app: teamspeak
    release: teamspeak-app
  annotations:
    meta.helm.sh/release-name: teamspeak-app
    meta.helm.sh/release-namespace: teamspeak
    ingress.cilium.io/loadbalancer-mode: shared
    io.cilium/lb-ipam-ips: 192.168.2.13
spec:
  ports:
    - name: teamspeak-voice
      protocol: UDP
      port: 9987
      targetPort: 9987
  selector:
    app: teamspeak
    release: teamspeak-app
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
