apiVersion: v1
kind: Service
metadata:
  name: teamspeak-app-tcp
  namespace: teamspeak
  labels:
    app: teamspeak
    release: teamspeak-app
  annotations:
    meta.helm.sh/release-name: teamspeak-app
    meta.helm.sh/release-namespace: teamspeak
    metallb.universe.tf/allow-shared-ip: "teamspeak"
    metallb.universe.tf/loadBalancerIPs: 192.168.2.48
spec:
  ports:
    - name: teamspeak-filetransfer
      protocol: TCP
      port: 30033
      targetPort: 30033
    - name: teamspeak-serverquery
      protocol: TCP
      port: 10011
      targetPort: 10011
  selector:
    app: teamspeak
    release: teamspeak-app
  type: LoadBalancer