apiVersion: v1
kind: Service
metadata:
  name: server-tcp
  namespace: teamspeak
  labels:
    app: teamspeak
    release: teamspeak-app
  annotations:
    meta.helm.sh/release-name: teamspeak-app
    meta.helm.sh/release-namespace: teamspeak
    ingress.cilium.io/loadbalancer-mode: shared
    io.cilium/lb-ipam-ips: 192.168.2.14
spec:
  ports:
    - name: teamspeak-filetransfer
      protocol: TCP
      port: 30033
      targetPort: 30033
    - name: teamspeak-serverquery
      protocol: TCP
      port: 10011
      targetPort: 10011
  selector:
    app: teamspeak
    release: teamspeak-app
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
