---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stammkneipe-dev-runner
  namespace: stammkneipe-dev
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.58.2
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
      - kind: Secret
        name: runner-config