---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stammkneipe-dev
resources:
  - ./helmrelease.yaml
secretGenerator:
  - name: runner-config
    namespace: flux-system
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
labels:
  - pairs:
      app.kubernetes.io/name: stammkneipe-dev-runner
      app.kubernetes.io/instance: stammkneipe-dev-runner
