---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teamspeak-mariadb
  namespace: teamspeak
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb
      version: 12.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
      - kind: Secret
        name: mariadb-config