---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - ./helmrelease.yaml
secretGenerator:
  - name: server-config
    namespace: flux-system
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
labels:
  - pairs:
      app.kubernetes.io/name: minecraft-server
      app.kubernetes.io/instance: minecraft-server
