apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels:
      io.kubernetes.service.name: ingress-nginx-controller
  interfaces:
  - ^eth[0-9]+
  externalIPs: false
  loadBalancerIPs: false
