---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stammkneipe-dev
resources:
  - https://gitlab.com/stammkneipe.dev/gitlab-runner-operator/-/tree/main/config/default?ref_type=heads
labels:
  - pairs:
      app.kubernetes.io/name: stammkneipe-dev-runner-operator
      app.kubernetes.io/instance: stammkneipe-dev-runner-operator
