apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave-gitops-dashboard.yaml
secretGenerator:
  - name: basic-auth-gitops-ui
    namespace: flux-system
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
  - networkpolicy.yaml