adminUser:
    create: ENC[AES256_GCM,data:pQv4zQ==,iv:xxKtoldFYXQMj5fy2TWIJgFHV+9syDZH1QZ6APTMmi4=,tag:po8woxJLwbomBKJDREi2Gg==,type:bool]
    passwordHash: ENC[AES256_GCM,data:W7lihO5o7VeMbkHyxcXFeo2uqPC88tnEL//1xYI23AHcMdbl0fg1+Cf2L6QRWB2IN/v1i3COeQ4e8u1+,iv:8B9xtYQbHvhT2zvHT9DZZpo5tcXcHsE1t9hY5t2GacU=,tag:dxsP2WLIzC7mI6BeK9j5EA==,type:str]
    username: ENC[AES256_GCM,data:jcfV9eU=,iv:40lP6xJE8ddM+FuErWI+oAlqRwLg9qYi/c3nB2dyj7Y=,tag:z+PrQrjn9e4Amv2/HeF9KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cmc4xg8fnd2rwplq8jwd7m0suym5zfdrqdwtwnw8qlv4cex2847s0a2muy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVkxsQSs5YjE0b0ZKMEs5
            NGdRSVhLOFM3RWFvUmxoWmE0Y05WTXFORW1vCjNOcGpHcDNnelJ3bDFjWWFCcmIv
            TnBVdXlvRGxLMERjSlBUS3JJTll2dVEKLS0tIDZUNXFWYkJuTVVQbGREZ2dHYWdh
            TWg1cUJFOHZEbS9HeFFvVFEreUwyUUEK5F2b+U2P+ixjt3BDsxTNoKMtUeiYSfco
            FWfe7jWziEGokPHMHACNGIDqKzoaCUW4XCfISF+trrlKnsmgNZT9Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T13:20:58Z"
    mac: ENC[AES256_GCM,data:4XlroFMKAQOoQ1hmj8jQx8SY3Ao91JgAnXi6Vt4MWyjY7/zyCvM0eUzFcC0xYkcDboFNlCr4O0K5g0UUHH9w/LLIpdriezc+dezJOWyyRUcFBEasbfHEx8lgC4oIUtyzF27Ao51YjyNdZ5Hob9Pdw8qI3fzOUtRpV86pjLxmaJw=,iv:3/169T5mD8V670e3BPoPSP3kFLLnUTi3jWC1NWrRQDs=,tag:2tGrwP1vbULygRKOLog7Bg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
