---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs
resources:
  - ./configmap.yaml
labels:
  - pairs:
      app.kubernetes.io/name: openebs-jiva
      app.kubernetes.io/instance: openebs-jiva
