# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: sharedat-app
#   namespace: flux-system
# spec:
#   path: ./kubernetes/apps/sharedat/sharedat/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: sharedat-db
#   namespace: flux-system
# spec:
#   path: ./kubernetes/apps/sharedat/sharedat/mariadb
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shlink
  namespace: flux-system
spec:
  path: ./kubernetes/apps/sharedat/sharedat/shlink
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age